/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * OrderPlacedView.java
 *
 * Created on 2011-mar-09, 11:57:00
 */

package imat;

import javax.swing.JPanel;

/**
 *
 * @author Boel_
 */
public class OrderPlacedView extends javax.swing.JPanel {

    /** Creates new form OrderPlacedView */
    public OrderPlacedView() {
        initComponents();
    }

    public HeaderPanel2 getOrderPlacedHeaderPanel() {
        return orderPlacedHeaderPanel;
    }

    public JPanel getOrderPlacedReciptPanel() {
        return orderPlacedReciptPanel;
    }

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        orderPlacedHeaderPanel = new imat.HeaderPanel2();
        orderPlacedReciptPanel = new javax.swing.JPanel();

        setName("Form"); // NOI18N

        orderPlacedHeaderPanel.setName("orderPlacedHeaderPanel"); // NOI18N

        orderPlacedReciptPanel.setName("orderPlacedReciptPanel"); // NOI18N

        javax.swing.GroupLayout orderPlacedReciptPanelLayout = new javax.swing.GroupLayout(orderPlacedReciptPanel);
        orderPlacedReciptPanel.setLayout(orderPlacedReciptPanelLayout);
        orderPlacedReciptPanelLayout.setHorizontalGroup(
            orderPlacedReciptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 639, Short.MAX_VALUE)
        );
        orderPlacedReciptPanelLayout.setVerticalGroup(
            orderPlacedReciptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 294, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(orderPlacedReciptPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(orderPlacedHeaderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(orderPlacedHeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(orderPlacedReciptPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private imat.HeaderPanel2 orderPlacedHeaderPanel;
    private javax.swing.JPanel orderPlacedReciptPanel;
    // End of variables declaration//GEN-END:variables

}
