/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * shoppingList.java
 *
 * Created on 2011-feb-28, 22:11:19
 */

package imat;

/**
 *
 * @author Boel_
 */
public class shoppingList extends javax.swing.JPanel {

    /** Creates new form shoppingList */
    public shoppingList() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        shoppingListTopPanel = new javax.swing.JPanel();
        shoppingListHeader = new javax.swing.JLabel();
        shoppingListName = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        shoppingListBottomPanel = new javax.swing.JPanel();
        shoppingListAddRow = new javax.swing.JButton();
        shoppingListRowPanel = new javax.swing.JPanel();
        shoppingListRow1 = new imat.ShoppingListRow();
        shoppingListScrollBar = new javax.swing.JScrollBar();

        setName("Form"); // NOI18N

        shoppingListTopPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        shoppingListTopPanel.setName("shoppingListTopPanel"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(imat.IMatApp.class).getContext().getResourceMap(shoppingList.class);
        shoppingListHeader.setFont(resourceMap.getFont("shoppingListHeader.font")); // NOI18N
        shoppingListHeader.setText(resourceMap.getString("shoppingListHeader.text")); // NOI18N
        shoppingListHeader.setName("shoppingListHeader"); // NOI18N

        shoppingListName.setFont(resourceMap.getFont("shoppingListName.font")); // NOI18N
        shoppingListName.setText(resourceMap.getString("shoppingListName.text")); // NOI18N
        shoppingListName.setName("shoppingListName"); // NOI18N

        jButton1.setFont(resourceMap.getFont("jButton1.font")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N

        javax.swing.GroupLayout shoppingListTopPanelLayout = new javax.swing.GroupLayout(shoppingListTopPanel);
        shoppingListTopPanel.setLayout(shoppingListTopPanelLayout);
        shoppingListTopPanelLayout.setHorizontalGroup(
            shoppingListTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(shoppingListName, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, shoppingListTopPanelLayout.createSequentialGroup()
                .addComponent(shoppingListHeader, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1))
        );
        shoppingListTopPanelLayout.setVerticalGroup(
            shoppingListTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shoppingListTopPanelLayout.createSequentialGroup()
                .addGroup(shoppingListTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(shoppingListHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shoppingListName, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
        );

        shoppingListBottomPanel.setName("shoppingListBottomPanel"); // NOI18N

        shoppingListAddRow.setFont(resourceMap.getFont("shoppingListAddRow.font")); // NOI18N
        shoppingListAddRow.setText(resourceMap.getString("shoppingListAddRow.text")); // NOI18N
        shoppingListAddRow.setName("shoppingListAddRow"); // NOI18N
        shoppingListAddRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shoppingListAddRowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout shoppingListBottomPanelLayout = new javax.swing.GroupLayout(shoppingListBottomPanel);
        shoppingListBottomPanel.setLayout(shoppingListBottomPanelLayout);
        shoppingListBottomPanelLayout.setHorizontalGroup(
            shoppingListBottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(shoppingListAddRow, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
        );
        shoppingListBottomPanelLayout.setVerticalGroup(
            shoppingListBottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(shoppingListAddRow, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
        );

        shoppingListRowPanel.setName("shoppingListRowPanel"); // NOI18N

        shoppingListRow1.setName("shoppingListRow1"); // NOI18N

        javax.swing.GroupLayout shoppingListRowPanelLayout = new javax.swing.GroupLayout(shoppingListRowPanel);
        shoppingListRowPanel.setLayout(shoppingListRowPanelLayout);
        shoppingListRowPanelLayout.setHorizontalGroup(
            shoppingListRowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shoppingListRowPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(shoppingListRow1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        shoppingListRowPanelLayout.setVerticalGroup(
            shoppingListRowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shoppingListRowPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(shoppingListRow1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(257, Short.MAX_VALUE))
        );

        shoppingListScrollBar.setName("shoppingListScrollBar"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(shoppingListTopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(shoppingListBottomPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(shoppingListRowPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shoppingListScrollBar, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(shoppingListTopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(shoppingListScrollBar, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                    .addComponent(shoppingListRowPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shoppingListBottomPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void shoppingListAddRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shoppingListAddRowActionPerformed
        // TODO: Add rows!
        //shoppingListRowPanel.add(new ShoppingListRow());
    }//GEN-LAST:event_shoppingListAddRowActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton shoppingListAddRow;
    private javax.swing.JPanel shoppingListBottomPanel;
    private javax.swing.JLabel shoppingListHeader;
    private javax.swing.JTextField shoppingListName;
    private imat.ShoppingListRow shoppingListRow1;
    private javax.swing.JPanel shoppingListRowPanel;
    private javax.swing.JScrollBar shoppingListScrollBar;
    private javax.swing.JPanel shoppingListTopPanel;
    // End of variables declaration//GEN-END:variables

}
