/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Receipt.java
 *
 * Created on 2011-mar-10, 08:08:22
 */

package imat;

import se.chalmers.ait.dat215.project.Order;
import se.chalmers.ait.dat215.project.ShoppingItem;

public class Receipt extends javax.swing.JPanel {

    //private static int ordernumber;

    /** Creates new form Receipt */
    public Receipt() {
        initComponents();
    }

    public void addReceiptRow(ShoppingItem item)
    {
       ReceiptRow row = new ReceiptRow();
       row.setReceiptRowAmountLabel(item.getAmount());
       row.setReceiptRowNameLabel(item.getProduct());
       row.setReceiptRowPriceLabel(item.getTotal()*item.getAmount());
       receiptRowPanel.add(row);
       receiptRowPanel.repaint();
       receiptRowPanel.revalidate();
    }

    public void setReceiptDate(Order order)
    {
        dateLabel.setText("Datum: "+order.getDate().getYear()+"-"+order.getDate().getMonth()+"-"+order.getDate().getDay());
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateLabel = new javax.swing.JLabel();
        receiptRowPanel = new javax.swing.JPanel();

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(imat.IMatApp.class).getContext().getResourceMap(Receipt.class);
        dateLabel.setFont(resourceMap.getFont("dateLabel.font")); // NOI18N
        dateLabel.setText(resourceMap.getString("dateLabel.text")); // NOI18N
        dateLabel.setName("dateLabel"); // NOI18N

        receiptRowPanel.setName("receiptRowPanel"); // NOI18N

        javax.swing.GroupLayout receiptRowPanelLayout = new javax.swing.GroupLayout(receiptRowPanel);
        receiptRowPanel.setLayout(receiptRowPanelLayout);
        receiptRowPanelLayout.setHorizontalGroup(
            receiptRowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 331, Short.MAX_VALUE)
        );
        receiptRowPanelLayout.setVerticalGroup(
            receiptRowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 354, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
            .addComponent(receiptRowPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(receiptRowPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateLabel;
    private javax.swing.JPanel receiptRowPanel;
    // End of variables declaration//GEN-END:variables

}
