/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SearchView.java
 *
 * Created on 2011-mar-04, 10:27:16
 */

package imat;

/**
 *
 * @author Boel_
 */
public class SearchView extends javax.swing.JPanel {

    /** Creates new form SearchView */
    public SearchView() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchScrollBar = new javax.swing.JScrollBar();
        searchBreadcrumbPanel = new javax.swing.JPanel();
        searchHeaderPanel = new imat.HeaderPanel2();
        searchDisplayPanel = new javax.swing.JPanel();

        setName("Form"); // NOI18N

        searchScrollBar.setName("searchScrollBar"); // NOI18N

        searchBreadcrumbPanel.setName("searchBreadcrumbPanel"); // NOI18N

        javax.swing.GroupLayout searchBreadcrumbPanelLayout = new javax.swing.GroupLayout(searchBreadcrumbPanel);
        searchBreadcrumbPanel.setLayout(searchBreadcrumbPanelLayout);
        searchBreadcrumbPanelLayout.setHorizontalGroup(
            searchBreadcrumbPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 755, Short.MAX_VALUE)
        );
        searchBreadcrumbPanelLayout.setVerticalGroup(
            searchBreadcrumbPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 57, Short.MAX_VALUE)
        );

        searchHeaderPanel.setName("searchHeaderPanel"); // NOI18N

        searchDisplayPanel.setName("searchDisplayPanel"); // NOI18N

        javax.swing.GroupLayout searchDisplayPanelLayout = new javax.swing.GroupLayout(searchDisplayPanel);
        searchDisplayPanel.setLayout(searchDisplayPanelLayout);
        searchDisplayPanelLayout.setHorizontalGroup(
            searchDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 765, Short.MAX_VALUE)
        );
        searchDisplayPanelLayout.setVerticalGroup(
            searchDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(searchBreadcrumbPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(searchDisplayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(searchHeaderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchScrollBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchScrollBar, javax.swing.GroupLayout.DEFAULT_SIZE, 767, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchHeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchBreadcrumbPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(329, 329, 329)
                .addComponent(searchDisplayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel searchBreadcrumbPanel;
    private javax.swing.JPanel searchDisplayPanel;
    private imat.HeaderPanel2 searchHeaderPanel;
    private javax.swing.JScrollBar searchScrollBar;
    // End of variables declaration//GEN-END:variables

}
